# Basic
title: YEQING.RUN
subtitle: 夜風凜凜，獨回望舊事前塵。
description: Android Developer.
creator: <a href="https://yeqing.run">me@yeiqng.run</a>

url: "https://yeqing.run"

permalink: /:year:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
# cover_color: red

# The blog button should not be removed.
blog_button:
    title: 进入首页
    description: 进入首页

# Navigation buttons in the front page.
nav:
     - {title: 界面设计, description: 界面设计, url: 'https://yeqing.run/ui/'}
     - {title: 动效设计, description: 动效设计, url: 'https://yeqing.run/ae/'}
     - {title: 三维设计, description: 三维设计, url: 'https://yeqing.run/3d/'}
     - {title: 产品设计, description: 产品设计, url: 'https://yeqing.run/pm/'}
     - {title: 野生技术, description: 野生技术, url: 'https://yeqing.run/it/'}
     - {title: 资源分享, description: 资源分享, url: 'https://yeqing.run/rs/'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    github: yeqing112
    mail: me@yeiqng.run

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host