# Basic
title: YEQING.RUN
subtitle: 井与陆地，海和岛屿。
description: Android Developer.
creator: <a href="https://yeqing.run">@yeiqng.run</a>

url: "https://yeqing.run"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
# cover_color: red

# The blog button should not be removed.
blog_button:
    title: 首页
    description: 首页

# Navigation buttons in the front page.
nav:
    # - {title: 技术, description: 我自己写的一些野生技术文章，也有转载大咖的文章, url: 'https://github.com/yeqing112/'}
    # - {title: 界面, description: 界面设计, url: 'https://github.com/yeqing112/'}
    # - {title: 动效, description: 二维动效, url: 'https://github.com/yeqing112/'}
    # - {title: 三维, description: 三维设计, url: 'https://github.com/yeqing112/'}
    # - {title: 产品, description: 产品设计与运营, url: 'https://github.com/yeqing112/'}
    # - {title: 资源, description: 优质资源分享, url: 'https://github.com/yeqing112/'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    github: yeqing112
    mail: 51025826@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
    
# Collections
collections:
 category:
  output: true
  permalink: /:collection/:title